// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    Auth: typeof import('./src/components/auth/Auth.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Input: typeof import('./src/components/forms/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
