// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    Auth: typeof import('./src/components/auth/Auth.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    Dashboard: typeof import('./src/components/sidebar/Dashboard.vue')['default']
    DeleteFileModal: typeof import('./src/components/modals/DeleteFileModal.vue')['default']
    FileInformation: typeof import('./src/components/modals/FileInformation.vue')['default']
    FileInformationModal: typeof import('./src/components/modals/FileInformationModal.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    IconCheck: typeof import('~icons/ic/on-check')['default']
    Input: typeof import('./src/components/forms/Input.vue')['default']
    InputWithOverlappingLabel: typeof import('./src/components/forms/InputWithOverlappingLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Toast: typeof import('./src/components/toast/Toast.vue')['default']
    Upload: typeof import('./src/components/upload/Upload.vue')['default']
  }
}
