// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    AlbumSettingsModal: typeof import('./src/components/modals/AlbumSettingsModal.vue')['default']
    Breadcrumbs: typeof import('./src/components/breadcrumbs/Breadcrumbs.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    DeleteFileModal: typeof import('./src/components/modals/DeleteFileModal.vue')['default']
    FileInformationModal: typeof import('./src/components/modals/FileInformationModal.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Input: typeof import('./src/components/forms/Input.vue')['default']
    InputWithOverlappingLabel: typeof import('./src/components/forms/InputWithOverlappingLabel.vue')['default']
    Masonry: typeof import('./src/components/masonry/Masonry.vue')['default']
    MasonryPublic: typeof import('./src/components/masonry/MasonryPublic.vue')['default']
    NewAlbumModal: typeof import('./src/components/modals/NewAlbumModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Toast: typeof import('./src/components/toast/Toast.vue')['default']
    Upload: typeof import('./src/components/upload/Upload.vue')['default']
    UsersTable: typeof import('./src/components/table/UsersTable.vue')['default']
  }
}
