// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlbumDropdown: typeof import('./src/components/dropdown/AlbumDropdown.vue')['default']
    AlbumSettingsModal: typeof import('./src/components/modals/AlbumSettingsModal.vue')['default']
    Breadcrumbs: typeof import('./src/components/breadcrumbs/Breadcrumbs.vue')['default']
    Button: typeof import('./src/components/buttons/Button.vue')['default']
    ChibiUploader: typeof import('./src/components/upload/ChibiUploader.vue')['default']
    CreateTag: typeof import('./src/components/tags/CreateTag.vue')['default']
    DeleteFileModal: typeof import('./src/components/modals/DeleteFileModal.vue')['default']
    FileInformationModal: typeof import('./src/components/modals/FileInformationModal.vue')['default']
    FilesTable: typeof import('./src/components/table/FilesTable.vue')['default']
    FilesWrapper: typeof import('./src/components/wrappers/FilesWrapper.vue')['default']
    GenericConfirmationModal: typeof import('./src/components/modals/GenericConfirmationModal.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    Input: typeof import('./src/components/forms/Input.vue')['default']
    InputWithOverlappingLabel: typeof import('./src/components/forms/InputWithOverlappingLabel.vue')['default']
    InvitesTable: typeof import('./src/components/table/InvitesTable.vue')['default']
    ManageAlbumModal: typeof import('./src/components/modals/ManageAlbumModal.vue')['default']
    ManageUserModal: typeof import('./src/components/modals/ManageUserModal.vue')['default']
    Masonry: typeof import('./src/components/masonry/Masonry.vue')['default']
    MasonryPublic: typeof import('./src/components/masonry/MasonryPublic.vue')['default']
    NewAlbumModal: typeof import('./src/components/modals/NewAlbumModal.vue')['default']
    Pagination: typeof import('./src/components/pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./src/components/modals/SearchModal.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Tag: typeof import('./src/components/tags/Tag.vue')['default']
    Toast: typeof import('./src/components/toast/Toast.vue')['default']
    UsersTable: typeof import('./src/components/table/UsersTable.vue')['default']
  }
}
